/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.byteemperor.kobo_project;

import io.github.byteemperor.kobo_project.cli.KoboCtlCommand;
import picocli.CommandLine;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        CommandLine dt = new CommandLine(new KoboCtlCommand());
        int exitCode = dt.execute(args);
        System.exit(exitCode);

    }
}
